name: Import WordPress Content

on:
  workflow_dispatch:
    inputs:
      xml_file:
        description: 'WordPress XML file name (must be in repo)'
        required: true
        default: 'wordpress-export.xml'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Import WordPress content
        run: |
          bundle exec jekyll import wordpress --source ${{ github.event.inputs.xml_file }}
          
      - name: Commit imported content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Import WordPress content - $(date)" || exit 0
          git push